version: '3.1'

services:
  mongo:
    image: 'mongo'
    ports:
      - "4000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    command: |
      mongod --bind_ip_all 
      
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env.local
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env.local
    depends_on:
      - server
      - mongo